defmodule Spool.Repo.Migrations.AddTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :created_by, :text, null: false
      add :name, :text, null: false
      add :is_active, :boolean, default: true
      add :description, :text
      add :rep_unit, :text, null: false
      add :every, :bigint
      add :repeats_on, {:array, :text}, default: []
      add :monthly_on, :bigint, null: false
      add :last_completed, :utc_datetime_usec
      add :last_updated, :utc_datetime_usec, null: false
      add :assigned_to, {:array, :text}, default: []
      add :room_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:tasks)
  end
end
